"""add spaced repetition fields to study_sessions

Revision ID: 309472c83914
Revises: c45ce509b4ff
Create Date: 2026-05-30 10:14:28.931801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309472c83914'
down_revision: Union[str, Sequence[str], None] = 'c45ce509b4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('study_sessions', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_sessions', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_sessions', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('study_sessions', sa.Column('ease_factor', sa.Float(), server_default='2.5', nullable=False))
    op.add_column('study_sessions', sa.Column('interval_days', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'interval_days')
    op.drop_column('study_sessions', 'ease_factor')
    op.drop_column('study_sessions', 'review_count')
    op.drop_column('study_sessions', 'next_review_at')
    op.drop_column('study_sessions', 'last_reviewed_at')
    op.drop_column('study_sessions', 'created_at')
    # ### end Alembic commands ###
