"""add_user_id_to_study_sessions

Revision ID: c45ce509b4ff
Revises: b8e6de53b495
Create Date: 2026-05-19 22:47:11.645873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45ce509b4ff'
down_revision: Union[str, Sequence[str], None] = 'b8e6de53b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_column('study_sessions', 'user_id')
    # ### end Alembic commands ###
